kafka:
  clusters:
    - name: cluster-A
      bootstrapServers: localhost:9094
    # - name: cluster-B
    # bootstrapServers: localhost:9093
    # - name: cluster-C
    #   bootstrapServers: localhost:9094
    # schemaRegistry: http://localhost:8081
    # kafkaConnect:
    #   - name: worker1
    #     address: http://localhost:8083
